### ISSUE TITLE
Message Header Layering

### ISSUE THREAD

**Issue by braem** [braem/NetworkSim#1]
You will be providing the data structure to be able to send messages, but you do not have to send them in this issue.
1. 
   - Make a Segment interface that contains a message and a header.
   - Make a TCPSegment class that has both the message and the TCP header, extending from Segment. 
   - Make a UDPSegment class that has both the message and the UDP header, extending from Segment.
   - Calculate the checksum for the segment. You can have the headers also be inherited from say a SegmentHeader interface if you wish.
2. Make a IPDatagram class that has both a Segment object and a IP header.
3. Make a EthernetFrame class that has both an IPDatagram and a Frame header.

**Comment by rhdabe** [comment]
I am willing to take care of this issue, if that works.

Rhys

**Comment by rhdabe** [comment]
Nevermind, I guess I'm on thread stuff. All good.
